/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pileTrash.glb 
Author: Soph (https://sketchfab.com/scs7392)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pile-of-trash-1-704b8a67e25148ddafdef79faa30a868
Title: Pile of Trash-1
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/pileTrash.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Material__25} position={[-0.376, 0.33, -0.021]} />
    </group>
  )
}

useGLTF.preload('/pileTrash.glb')
